### ISSUE TITLE
Milestone 3 set up

### ISSUE THREAD

**Issue by stvhwrd** [SENG480/course#3]
- [ ]  Create a template document
- [ ]  Break down M3 into individual tasks
- [ ]  Assign individual tasks to team members

**Comment by stvhwrd** [comment]
Oof.  Sorry about that - wrong repo.
